name: games_deals_fschmatz
description: Flutter+Dart
publish_to: 'none'
version: 1.8.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider:
  shared_preferences:
  provider:
  url_launcher:
  webfeed:
  http:
  dynamic_value:
  share:
  easy_dynamic_theme:
  flutter_lints:
  cupertino_icons: ^1.0.2
  jiffy:
  dynamic_color: ^1.6.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: StoreIcons
      fonts:
        - asset: assets/StoreIcons.ttf
